-- MySQL Script generated by MySQL Workbench
-- Mon Aug 13 18:22:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notaire1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notaire1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notaire1` DEFAULT CHARACTER SET utf8 ;
USE `notaire1` ;

-- -----------------------------------------------------
-- Table `notaire1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notaire1`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(250) NULL,
  `type_user` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `photo` VARCHAR(250) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaire1`.`info_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notaire1`.`info_client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom_client` VARCHAR(45) NULL,
  `prenom_client` VARCHAR(45) NULL,
  `date_naissance` DATE NULL,
  `date_creation` DATETIME NULL,
  `userClID` INT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_info_cl_user_idx` (`userClID` ASC) VISIBLE,
  CONSTRAINT `fk_info_cl_user`
    FOREIGN KEY (`userClID`)
    REFERENCES `notaire1`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaire1`.`info_notaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notaire1`.`info_notaire` (
  `id_notaire` INT NOT NULL AUTO_INCREMENT,
  `nom_notaie` VARCHAR(45) NOT NULL,
  `prenom_notaire` VARCHAR(45) NOT NULL,
  `adresse_cabinet` VARCHAR(200) NOT NULL,
  `departement` VARCHAR(45) NOT NULL,
  `commune` VARCHAR(45) NOT NULL,
  `date_creation` DATE NOT NULL,
  `date_commision` DATE NOT NULL,
  `userNoID` INT NOT NULL,
  `long_adr` DOUBLE NULL,
  `lat_adr` DOUBLE NULL,
  PRIMARY KEY (`id_notaire`),
  UNIQUE INDEX `id_notaire_UNIQUE` (`id_notaire` ASC) VISIBLE,
  UNIQUE INDEX `userNoID_UNIQUE` (`userNoID` ASC) VISIBLE,
  CONSTRAINT `fk_not_user_id`
    FOREIGN KEY (`userNoID`)
    REFERENCES `notaire1`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaire1`.`notaire_reconnu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notaire1`.`notaire_reconnu` (
  `id_notaire_recon` INT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `juridiction` VARCHAR(45) NULL,
  `commune` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`id_notaire_recon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notaire1`.`rendez_vous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notaire1`.`rendez_vous` (
  `idrendez_vous` INT NOT NULL AUTO_INCREMENT,
  `date_rendez_vous` DATE NULL,
  `date_created` DATE NULL,
  `sujet_motif` VARCHAR(45) NULL,
  `motif_description` LONGTEXT NULL,
  `clientUserID` INT NOT NULL,
  `notaireUserID` INT NOT NULL,
  PRIMARY KEY (`idrendez_vous`),
  INDEX `fk_client_id_rd_idx` (`clientUserID` ASC) VISIBLE,
  INDEX `fk_notaire_id_rd_idx` (`notaireUserID` ASC) VISIBLE,
  CONSTRAINT `fk_client_id_rd`
    FOREIGN KEY (`clientUserID`)
    REFERENCES `notaire1`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notaire_id_rd`
    FOREIGN KEY (`notaireUserID`)
    REFERENCES `notaire1`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
